name: "🐞 BUG"
description: "기존 기능의 오류를 수정하고 시스템 안정성을 개선하기 위한 작업입니다."
labels: [bug]
title: "[BUG] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요 (ex: GH-1234)"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: "버그 요약 (Description)"
      description: "버그의 주요 증상과 문제를 간략히 설명해주세요 (ex: 로그인 시 오류 메시지 발생)"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "버그 상세 내용 (Details)"
      description: "버그가 발생한 상황과 재현 방법, 기대 결과 및 실제 결과를 작성해주세요"
      value: |
        **발생 환경:**  
        (ex: Chrome 브라우저, Windows 10, 버전 1.2.3)

        **문제 상황:**  
        (ex: 로그인 버튼 클릭 시 500 Internal Server Error 발생)

        **재현 방법:**  
          1. 
          2. 

        **기대 결과:**  
        (ex: 정상적으로 대시보드 페이지로 이동해야 합니다.)

        **실제 결과:**  
        (ex: 500 Internal Server Error가 발생하고 로그인에 실패합니다.)
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "버그 수정 체크리스트 (Tasks)"
      description: "버그를 해결하기 위해 필요한 작업 목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
        - [ ] Task3
    validations:
      required: true
