name: "📝 DEFAULT"
description: "기본 이슈 템플릿입니다."
labels: [default]
title: "[DEFAULT] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: description
    attributes:
      label: "이슈 요약 (Description)"
      description: "이슈에 대해 간략히 설명해주세요."
    validations:
      required: true
