name: "🗑️ DEL"
description: "불필요하거나 더 이상 사용되지 않는 기능을 제거하여 시스템을 간소화하고 유지보수성을 향상시키기 위한 작업입니다."
labels: [del]
title: "[DEL] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요 (ex: GH-1234)"
    validations:
      required: true
  
  - type: input
  id: currentTicket
  attributes:
    label: "현재 작업 Ticket Number"
    description: "이 기능을 위한 현재 작업의 Ticket Number를 기입해주세요 (ex: GH-5678)"
  validations:
    required: true

  - type: input
    id: description
    attributes:
      label: "기능 제거 요약 (Description)"
      description: "제거하려는 기능에 대해 간략히 설명해주세요 (ex: 사용되지 않는 설정 옵션 제거)"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "기능 제거 상세 내용 (Details)"
      description: "제거할 기능의 배경, 이유 및 기대되는 결과를 작성해주세요"
      value: |
        **작업 배경 및 목적:**  
        (ex: 이 기능은 더 이상 사용되지 않아 시스템을 복잡하게 만들고 있습니다.)

        **제거할 항목:**  
        (ex: 대시보드에 있는 '최근 활동' 위젯)

        **기대되는 결과:**  
        (ex: UI가 간결해지고 유지보수성이 개선됩니다.)
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "기능 제거 체크리스트 (Tasks)"
      description: "제거 작업에 필요한 세부 작업 목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
        - [ ] Task3
    validations:
      required: true
