name: "✨ FEATURE"
description: "새로운 기능을 추가하거나 시스템을 확장하기 위한 작업입니다."
labels: [feature]
title: "[FEATURE] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요 (ex: GH-1234)"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: "기능 요약 (Description)"
      description: "새로운 기능의 목적과 주요 내용을 간략히 작성해주세요 (ex: 사용자 프로필 편집 기능 추가)"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "기능 상세 내용 (Details)"
      description: "기능의 배경, 목적, 기대되는 결과 및 주요 요구사항을 구체적으로 작성해주세요"
      value: |
        **기능 배경 및 목적:**  
        (ex: 사용자가 자신의 프로필 정보를 직접 수정할 수 있는 기능이 필요합니다.)

        **기능 설명:**  
        (ex: 프로필 사진, 사용자 이름, 비밀번호를 수정할 수 있는 UI 제공)

        **기대되는 결과:**  
        (ex: 사용자가 쉽게 프로필을 수정하고 저장할 수 있습니다.)
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "기능 개발 체크리스트 (Tasks)"
      description: "해당 기능을 개발하기 위해 필요한 작업 목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
        - [ ] Task3
    validations:
      required: true
