name: "🛠️ FIX"
description: "작은 오류나 사소한 문제를 해결하기 위한 작업입니다. 기능적 문제는 아니지만 코드, UI, 설정 등의 사소한 부분을 수정합니다."
labels: [fix]
title: "[FIX] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요 (ex: GH-1234)"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: "수정 요약 (Description)"
      description: "수정하려는 문제에 대해 간략히 설명해주세요 (ex: 버튼 텍스트 오타 수정)"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "수정 상세 내용 (Details)"
      description: "수정이 필요한 문제의 배경, 원인 및 기대되는 결과를 작성해주세요"
      value: |
        **작업 배경 및 목적:**  
        (ex: 버튼 텍스트에 오타가 있어 사용자 혼란이 발생하고 있습니다.)

        **수정할 항목:**  
        (ex: 'Submit' 버튼 텍스트를 'Save'로 수정)

        **기대되는 결과:**  
        (ex: 사용자 혼란이 줄어들고 UI가 일관성을 유지합니다.)
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "수정 체크리스트 (Tasks)"
      description: "수정을 위해 필요한 작업 목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
        - [ ] Task3
    validations:
      required: true
