name: "@gather_here 이슈 생성"
description: "@gather_here레포에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다."
labels: [order]
title: "이슈 이름을 작성해주세요"

body:
  - type: radiobuttons
    id: issueType
    attributes:
      label: "이슈 유형 (Issue Type)"
      description: "해당하는 이슈 유형을 선택해주세요."
      options:
        - label: "🛠️ Refactor: 기존 코드를 개선하지만 기능은 변경되지 않습니다."
        - label: "✅ Update: 기존 기능을 수정하거나 개선합니다."
        - label: "🐞 Bug: 오류나 문제를 수정합니다."
        - label: "🎨 Style: 코드 스타일이나 UI를 개선합니다 (기능 변경 없음)."
        - label: "✨ Feature: 새로운 기능을 추가합니다."
        - label: "🗑️ Delete: 불필요한 기능이나 코드를 제거합니다."
        - label: "🛠️ Fix: 사소한 문제나 오류를 수정합니다."
    validations:
      required: true

  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요 (ex: GH-1)"
    validations:
      required: true

  - type: input
    id: subIssueKey
    attributes:
      label: "하위 이슈 Ticket Number"
      description: "해당하는 하위 이슈의 Ticket Number를 입력해주세요 (하위 이슈가 없으면 PASS하셔도 됩니다) (ex: GH-18)"
    validations:
      required: false

  - type: input
    id: description
    attributes:
      label: "이슈 내용(Description)"
      description: "이슈에 대해서 간략히 설명해주세요"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "상세 내용(Details)"
      description: "이슈에 대해서 자세히 설명해주세요"
      value: |
        - About Details
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "체크리스트(Tasks)"
      description: "해당 이슈에 대해 필요한 작업 목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
