name: "✅ UPDATE"
description: "기존 기능을 개선하거나 성능을 향상시키는 작업입니다. 사용자 경험을 개선하거나 시스템 효율성을 높이기 위한 업데이트를 수행합니다."
labels: [update]
title: "[UPDATE] 이슈 이름을 작성해주세요"

body:
  - type: input
    id: parentKey
    attributes:
      label: "상위 작업 Ticket Number"
      description: "상위 작업의 Ticket Number를 기입해주세요 (ex: GH-1234)"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: "업데이트 요약 (Description)"
      description: "이 업데이트의 목적과 주요 내용을 간략히 작성해주세요 (ex: 로그인 속도 개선)"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "업데이트 상세 내용 (Details)"
      description: "작업의 배경, 목적 및 기대되는 결과를 자세히 작성해주세요"
      value: |
        **작업 배경 및 목적:**  
        (ex: 로그인 시 느린 응답 시간으로 사용자 불만이 증가하고 있습니다.)

        **업데이트 내용:**  
        (ex: 로그인 API를 최적화하여 응답 시간을 단축합니다.)

        **기대되는 결과:**  
        (ex: 로그인 응답 시간이 3초에서 1초 이내로 개선됩니다.)
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "업데이트 체크리스트 (Tasks)"
      description: "업데이트에 필요한 작업 목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
        - [ ] Task3
    validations:
      required: true
